# Generated by Django 5.0.7 on 2024-08-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Укажите номер версии', null=True, verbose_name='Номер')),
                ('name', models.CharField(help_text='Введите название версии', max_length=100, verbose_name='Название')),
                ('indication', models.BooleanField(default=False, verbose_name='Активная версия')),
                ('product', models.ForeignKey(blank=True, help_text='выберите продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Версия продукта',
                'verbose_name_plural': 'Версии продуктов',
            },
        ),
    ]
