# Generated by Django 5.0.7 on 2024-08-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_version_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(blank=True, help_text='выберите продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version', to='catalog.product', verbose_name='продукт'),
        ),
    ]
