# Generated by Django 4.2.2 on 2024-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name', 'price', 'created_at', 'updated_at'], 'permissions': [('can_edit_category', 'Can edit bread'), ('can_edit_description', 'Can edit description'), ('set_published_status', 'Can publish product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
