# Generated by Django 4.2.2 on 2024-09-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name', 'price', 'created_at', 'updated_at'], 'permissions': [('can_edit_category', 'Can edit category'), ('can_edit_description', 'Can edit description'), ('set_published_status', 'Can publish product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
